#Fileserver 
#########################################
#Fileversion:   Version 1.1
#Author:        Raveendran Shajiran
#Created on:    13.03.2021
#########################################

#VIRTUAL MACHINE SETTINGS
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "Fileserver (Samba)"
        vb.memory = "2048"
        vb.cpus = 2
        vb.gui = true
    end 
end
