#Fileserver 
#########################################
#Fileversion:   Version 1.1
#Author:        Raveendran Shajiran
#Created on:    13.03.2021
#########################################

#VIRTUAL MACHINE SETTINGS
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "Fileserver (Samba)"
        vb.memory = "2048"
        vb.cpus = 2
        vb.gui = true
    end 

    #NETWORK SETTINGS
    config.vm.network :public_network

    #PORTFORWARD
    config.vm.network :forwarded_port, guest: 80, host: 8000
    config.vm.network :forwarded_port, guest: 22, host: 2200, id: "ssh"

    #SAMBA INSTALLATION
    SCRIPT_INSTALL = <<-SCRIPT
        set -e
        
        apt-get -y update
        apt-get -y upgrade
        apt-get -y install samba
        
        sudo cp /etc/samba/smb.conf /etc/samba/smb.conf-backup
        sudo rm /etc/samba/smb.conf
    SCRIPT

    config.vm.provision :shell, inline: SCRIPT_INSTALL

    config.vm.provision "file", 
        source: "https://raw.githubusercontent.com/shajiran/m300_lb/main/lb2/smb.conf", 
        destination: "/tmp/smb.conf"
end
