#Fileserver 
#########################################
#Fileversion:   Version 1.1
#Author:        Raveendran Shajiran
#Created on:    13.03.2021
#########################################

#VAGRANT SETTINGS
Vagrant.configure("2") do |config|
    
    #VIRTUAL MACHINE SETTINGS
    config.vm.box = "ubuntu/trusty64"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "Fileserver (Samba)"
        vb.memory = "2048"
        vb.cpus = 2
        vb.gui = true
    end 

    #NETWORK SETTINGS
    config.vm.network "public_network", ip: "192.168.1.200"

    #PORTFORWARD
    config.vm.network :forwarded_port, guest: 80, host: 8000
    config.vm.network :forwarded_port, guest: 22, host: 2200, id: "ssh"

    #PROVINIONING / SAMBA INSTALLATION
    SCRIPT_INSTALL = <<-SCRIPT
        set -e
        
        apt-get -y update
        apt-get -y upgrade
        apt-get -y install samba
        
        sudo cp /etc/samba/smb.conf /etc/samba/smb.conf-backup
        sudo rm /etc/samba/smb.conf

        sudo wget -P /etc/samba/ https://raw.githubusercontent.com/shajiran/m300_lb/main/lb2/smb.conf 
    
        LOGIN=test
        PASS=mypassword
        
        sudo mkdir /home/$LOGIN

        echo -ne "$PASS\n$PASS\n" | sudo adduser $LOGIN
        sudo addgroup $LOGIN $LOGIN

        echo -ne "$PASS\n$PASS\n" | sudo smbpasswd -a -s $LOGIN
        
        sudo chown $LOGIN:$LOGIN /home/$LOGIN
        sudo chmod 2770 /home/$LOGIN

        sudo /etc/init.d/samba restart

    SCRIPT

    config.vm.provision :shell, inline: SCRIPT_INSTALL 

end
